// <auto-generated />
using System;
using BulldozerServer.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BulldozerServer.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240515160631_CreatePostsTable")]
    partial class CreatePostsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BulldozerServer.Domain.Group", b =>
                {
                    b.Property<Guid>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AllowanceOfPostage")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GroupId");

                    b.HasIndex("UserId");

                    b.ToTable("Group");
                });

            modelBuilder.Entity("BulldozerServer.Domain.MarketplacePosts.MarketplacePost", b =>
                {
                    b.Property<Guid>("MarketplacePostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPromoted")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MediaContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MarketplacePostId");

                    b.HasIndex("AuthorId");

                    b.HasIndex("GroupId");

                    b.ToTable("MarketplacePost");
                });

            modelBuilder.Entity("BulldozerServer.Domain.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("BirthDay")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Cart", b =>
                {
                    b.Property<Guid>("PeopleThatPlacedInCartUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PostsInCartMarketplacePostId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PeopleThatPlacedInCartUserId", "PostsInCartMarketplacePostId");

                    b.HasIndex("PostsInCartMarketplacePostId");

                    b.ToTable("Cart");
                });

            modelBuilder.Entity("PostFavors", b =>
                {
                    b.Property<Guid>("FavoritePostsMarketplacePostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PeopleThatFavoredUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("FavoritePostsMarketplacePostId", "PeopleThatFavoredUserId");

                    b.HasIndex("PeopleThatFavoredUserId");

                    b.ToTable("PostFavors");
                });

            modelBuilder.Entity("BulldozerServer.Domain.Group", b =>
                {
                    b.HasOne("BulldozerServer.Domain.User", "User")
                        .WithMany("Groups")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BulldozerServer.Domain.MarketplacePosts.MarketplacePost", b =>
                {
                    b.HasOne("BulldozerServer.Domain.User", "Author")
                        .WithMany("MarketplacePosts")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BulldozerServer.Domain.Group", "Group")
                        .WithMany("MarketplacePosts")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Cart", b =>
                {
                    b.HasOne("BulldozerServer.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("PeopleThatPlacedInCartUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BulldozerServer.Domain.MarketplacePosts.MarketplacePost", null)
                        .WithMany()
                        .HasForeignKey("PostsInCartMarketplacePostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PostFavors", b =>
                {
                    b.HasOne("BulldozerServer.Domain.MarketplacePosts.MarketplacePost", null)
                        .WithMany()
                        .HasForeignKey("FavoritePostsMarketplacePostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BulldozerServer.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("PeopleThatFavoredUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BulldozerServer.Domain.Group", b =>
                {
                    b.Navigation("MarketplacePosts");
                });

            modelBuilder.Entity("BulldozerServer.Domain.User", b =>
                {
                    b.Navigation("Groups");

                    b.Navigation("MarketplacePosts");
                });
#pragma warning restore 612, 618
        }
    }
}
